version: '3'

services:
  redis:
    container_name: docker-gitlab-redis
    restart: always
    image: sameersbn/redis:3.0.6
    sysctls:
      net.core.somaxconn: '511'
    command:
    - --loglevel warning
    volumes:
    - $PWD/docker-gitlab-data/redis:/var/lib/redis:Z
    environment:    
    - TZ=Asia/Taipei
  postgresql:
    container_name: docker-gitlab-postgresql
    restart: always
    image: sameersbn/postgresql:9.6-2
    volumes:
    - $PWD/docker-gitlab-data/postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
    - TZ=Asia/Taipei
  gitlab:
    container_name: docker-gitlab
    restart: always
    image: sameersbn/gitlab:9.5.5
    depends_on:
    - redis
    - postgresql
    ports:
    - "10081:80"
    volumes:
    - $PWD/docker-gitlab-data/gitlab:/home/git/data:Z
    environment:
    - DEBUG=false
    - GITLAB_RELATIVE_URL_ROOT=/gitlab
    # gitlab頁面顯示用
    - GITLAB_HOST=192.168.57.21
    # gitlab頁面顯示用
    - GITLAB_PORT=80
    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - TZ=Asia/Taipei
    - GITLAB_TIMEZONE=Taipei
    - GITLAB_HTTPS=false
    - SSL_SELF_SIGNED=false    
    - GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alphanumeric-string
    - GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alphanumeric-string
    - GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alphanumeric-string
    - LDAP_ENABLED=true
    - LDAP_LABEL=資拓AD登入
    - LDAP_ACTIVE_DIRECTORY=true
    - LDAP_HOST=192.168.2.12
    - LDAP_UID=sAMAccountName
    - LDAP_BIND_DN=iisildap@iead.local
    - LDAP_PASS=iisi@1qaz2wsx
    - LDAP_ALLOW_USERNAME_OR_EMAIL_LOGIN=true
    - LDAP_BASE=DC=iead,DC=local
    - LDAP_USER_ATTRIBUTE_USERNAME=sAMAccountName
    - LDAP_USER_ATTRIBUTE_MAIL=mail
    - LDAP_USER_ATTRIBUTE_NAME=name
    - LDAP_USER_FILTER=objectClass=person
    - NGINX_REAL_IP_TRUSTED_ADDRESSES=192.168.57.21




    
